### ISSUE TITLE
Is project still maintained?

### ISSUE THREAD

**Issue by jdlrobson** [nasirkhan/mediawiki-bootstrap#12]
This skin has been marked as unmaintained on https://www.mediawiki.org/wiki/Skin:MediaWikiBootstrap

It is currently not working with the latest version of Mediawiki.

Are new patches welcome here to fix this, or should the skin be archived on MediaWiki.org and github.com ?

Thanks in advance for your answer!

**Comment by nasirkhan** [comment]
Thank you for contacting me. 

This skin has not been tested with the latest version of Mediawiki. And you might be right that it might not work properly with the latest version. I was working on this skin alone and could not got enough time to update along with Mediawiki. But I will welcome you and anyone willing to fix the issues and make it compatible for the new version. 

I may try to update it even I planned to update the skin with Bootstrap 5. But unfortunately I can not tell you any fixed timeline for that.

**Comment by jdlrobson** [comment]
Nice! I will be happy to help!

**Comment by jdlrobson** [comment]
The above patch is the minimum needed here. If merged I can update the mediawiki page to show this as stable :)

It looks good! Nice work!  I hope you keep working on it!

**Comment by nasirkhan** [comment]
Thank you for your contribution. The pull request has been merged. 

I will try to work on this skin soon and will improve and fix the other issues.
