### ISSUE TITLE
MediaWiki:Sidebar is not working

### ISSUE THREAD

**Issue by nasirkhan** [nasirkhan/mediawiki-bootstrap#14]
The `MediaWiki:Sidebar` is not working as expected and changes on this is page is only visible to some of the pages.

**Comment by nasirkhan** [comment]
@jdlrobson Can you please help to fix this issue? I will try to convert the skin to Mustache but first I need to have a working version. Thanks

**Comment by jdlrobson** [comment]
I'm going to need more information about this one. Is this the sidebar you are referring to (it's displaying my side)?

<img width="609" alt="Screen Shot 2021-01-05 at 4 02 22 PM" src="https://user-images.githubusercontent.com/148752/103712719-676b9500-4f6f-11eb-93b3-4bc7f20a2191.png">

Can you provide some replication steps? Do I need any special config? What version of MediaWiki are you seeing this?

**Comment by nasirkhan** [comment]
Thanks for your reply. 

yes I am referring to this navigation/sidebar. Earlier it displayed the items I listed in the `MediaWiki:Sidebar` page, but now It is showing the list of items which are not on the `MediaWiki:Sidebar` page.  The default vector skin did not worked on my installation showing a number of errors, I am am not sure on a default environment where these used to show. I could not find any doc related to this type of skin, all of the doc referred to the Mustache version. 

I am using a fresh Mediawiki 1.35.1. I am testing this from a Windows 10 machine and had faced a number of issues while installing the Mediawiki, like the `liuggio\statsd-php-client` package files/class was missing and Vector skin was showing a number of errors. I used this skin and the site opened. 

I did noting special, installed the mediawiki and then added this skin and enabled it from the LocalSettings.php page. Then I faced the issue of this `sidebar`

**Comment by jdlrobson** [comment]
I'm going to need some more help debugging this one.

Here's the skin on https://skins-demo.wmflabs.org/wiki/MediaWiki:Sidebar?useskin=mediawikibootstrap
The custom link from MediaWiki:Sidebar is showing.

Could you share the wikitext inside your [[MediaWiki:Sidebar]] ?

**Comment by nasirkhan** [comment]
My [[MediaWiki:Sidebar]] contents are as following. 

```
* navigation
** mainpage|mainpage-description
** randompage-url|randompage
```

On the previous comment I may have not been able to describe the issue with enough details. I found a solution of the issue I was facing and now will have to spend some time to properly handle that. 

I was using the `$this->renderNavigation(array('SIDEBAR'));` code to display the sidebar. On the way to solve the issue I found that is is adding the `Tools` and `Other Languages` items and displaying as a single list. But I am sure previously it was not like that. When I could not find any related doc to understand what are the items available in the SIDEBAR array, I was thinking to create a new skin from scratch and faced a lot of issues, it would be really helpful if you can also look into that as well (https://www.mediawiki.org/wiki/Topic:W1034jb1bri73yjx). 

Now I replaced the current `$this->renderNavigation(array('SIDEBAR'));` line with the following code and it shows only the [[MediaWiki:Sidebar]] items. Can you suggest me some good doc which is helpful to rebuild/ build a new skin?

```
<?php
foreach ( $this->getSidebar() as $boxName => $box ) { ?>
	<!-- <div id="<?php echo Sanitizer::escapeId( $box['id'] ) ?>"<?php echo Linker::tooltip( $box['id'] ) ?>> -->
		<!-- <h5><?php echo htmlspecialchars( $box['header'] ); ?></h5> -->
		<!-- If you do not want the words "Navigation" or "Tools" to appear, you can safely remove the line above. -->

		<?php
		if (htmlspecialchars( $box['header'] ) == "Tools") {
			continue;
		}
		elseif (htmlspecialchars( $box['header'] ) == "In other languages") {
			continue;
		}
		elseif ( is_array( $box['content'] ) ) { ?>
			<!-- <ul class="nav navbar-nav navbar-right"> -->
				<?php
				foreach ( $box['content'] as $key => $item ) {
					echo $this->makeListItem( $key, $item );
				}
				?>
			<!-- </ul> -->
			<?php
		} else {
			echo $box['content'];
		}
		?>
	<!-- </div> -->
<?php } ?>
```

**Comment by jdlrobson** [comment]
I've opened https://phabricator.wikimedia.org/T271444 - looks like a general issue.

**Comment by nasirkhan** [comment]
Thanks for creating the task, I though I am the one who is facing this issue.

**Comment by nasirkhan** [comment]
@jdlrobson I just found that the skin is not responsive on mobile on my local installation, but your [demo](https://skins-demo.wmflabs.org/wiki/MediaWiki:Sidebar?useskin=mediawikibootstrap) is showing as expected. I am sure I did not used anything extra while I was developing the skin few years back. 

Are you using any additional extension and what is the best practice of making any skin responsive?

**Comment by jdlrobson** [comment]
Perhaps on your local install https://github.com/nasirkhan/mediawiki-bootstrap/blob/master/skin.json#L21 is not having any effect? 

Note the responsive key is only available in the upcoming 1.36 release (or currrent master).
https://github.com/wikimedia/mediawiki/blob/master/includes/skins/Skin.php#L165
https://github.com/wikimedia/mediawiki/commit/204ddf0522963696436bc22c325e781bed4a5c17

**Comment by nasirkhan** [comment]
Thank you for the clarification. 
The roadmap says Mediwawiki 1.36 stable will be released near mid 2021. I can see there are a number of released in wmf branch. Do you recommend to update any existing site to Mediawiki Master/ 1.36 now? Are all the core extensions (which are available in the stable archive) are compatible with the 1.36?

**Comment by jdlrobson** [comment]
It depends on the goal.

When developing I would always recommend installing and developing from the mediawiki master branch.


Wikimedia projects e.g wikipedia.org use the development branch so some stability is assumed but only for the extensions and skins it deploys. It changes every week so it's hard to keep up with 

If you are running a mediawiki site where stability is needed 1.35 is recommended.

For skins that need to work against 1.36 as well as 1.35 I would recommend first building a skin against 1.36 and later adding polyfills to make it backwards compatible. A few skins, notably Timeless use version_compare to do this.

**Comment by nasirkhan** [comment]
The goal is to have a responsive skin/ mediawiki website.

I run two mediawiki sites which were developed a few years ago and used
this MediaWikiBootstrap skin. Those sites do not update frequently and you
also mentioned dev branch updates weekly and it is hard to keep up with.

When you made this skin compatible with 1.35 I updated those sites to 1.35
as well. But then I found that the responsive behaviour is gone. It always
shows the desktop site from all the devices. But when the sites were built
a few years back the responsive behaviour was working as expected. Now I
need some assistance on updating the skin in a way so that the responsive
feature works again.


--
*Nasir Khan Saikat*
www.nasirkhn.com

**Comment by nasirkhan** [comment]
@jdlrobson 
adding viewport solves the issue of responsive design issue. 

By following you advice I will try to build a skin for 1.36 first and then will make it backwards compatible. Can you please let me know which one would be the right place to ask and discuss while building new skin?
