### ISSUE TITLE
Navbar-header not rendering properly in Internet Explorer 11. 

### ISSUE THREAD

**Issue by briarias07** [nasirkhan/mediawiki-bootstrap#7]
Navbar-header is rendering as a mobile device on IE 11.  Works great on Chrome and Firefox.

![ierenderissue](https://cloud.githubusercontent.com/assets/12955262/8236844/f89977a0-159f-11e5-90a6-ac1fc10a2125.PNG)
.

**Comment by narath** [comment]
Also an issue for us.

**Comment by nasirkhan** [comment]
i am sorry that you had to face this issue. i will look into this issue and update as soon as possible.

**Comment by snacke** [comment]
I'm having this problem too. Has any solution been found yet?
