### ISSUE TITLE
OutputPage:getModuleStyles; should define its position explicitly

### ISSUE THREAD

**Issue by clrh** [nasirkhan/mediawiki-bootstrap#9]
Hi,

On a fresh install of mediawiki:

<pre>
# HEAD of mediawiki
c2d388d (HEAD, origin/REL1_26, REL1_26) Add missing RELEASE-NOTES for backport.
4a0fa4b Fix exception in Import, when import of a revision fails
12568e1 Fix "Undefined property: DiffEngine::$seq" under HHVM in DairikiDiff.php
f465524 (tag: 1.26.2) Prep 1.26.2
</pre>

I got an error I do not understand:

<pre>
2016/02/09 09:59:38 [error] 1005#0: *46831177 FastCGI sent in stderr: "PHP message: PHP Warning:  OutputPage::getModuleStyles: style module should define its position explicitly: skins.mediawikibootstrap ResourceLoaderFileModule [Called from OutputPage::getModuleStyles in /var/www/mediawiki/includes/OutputPage.php at line 623] in /var/www/mediawiki/includes/debug/MWDebug.php on line 300
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /var/www/mediawiki/index.php:0
PHP message: PHP   2. MediaWiki->run() /var/www/mediawiki/index.php:41
PHP message: PHP   3. MediaWiki->main() /var/www/mediawiki/includes/MediaWiki.php:508
PHP message: PHP   4. OutputPage->output() /var/www/mediawiki/includes/MediaWiki.php:722
PHP message: PHP   5. SkinTemplate->outputPage() /var/www/mediawiki/includes/OutputPage.php:2326
PHP message: PHP   6. SkinTemplate->prepareQuickTemplate() /var/www/mediawiki/includes/skins/SkinTemplate.php:240
PHP message: PHP   7. Skin->bottomScripts() /var/www/mediawiki/includes/skins/SkinTemplate.php:427
PHP message: PHP   8. OutputPage->getBottomScripts() /var/www/mediawiki/includes/skins/Skin.php:619
PHP message: PHP   9. OutputPage->getScriptsForBottomQueue() /var/www/mediawiki/includes/OutputPage.php:3146
PHP message: PHP  10. OutputPage->getModuleStyles() /var/www/mediawiki/includes/OutputPage.php:3077
PHP message: PHP  11. wfLogWarning() /var/www/mediawiki/includes/OutputPage.php:623
PHP message: PHP  12. MWDebug::warning() /var/www/mediawiki/includes/GlobalFunctions.php:1222
PHP message: PHP  13. MWDebug::sendMessage() /var/www/mediawiki/includes/debug/MWDebug.php:155
PHP message: PHP  14. trigger_error() /var/www/mediawiki/includes/debug/MWDebug.php:300
PHP message: PHP Warning:  OutputPage::getModuleStyles: style module should define its position explicitly: skins.mediawikibootstrap ResourceLoaderFileModule [Called from OutputPage::getModuleStyles in /var/www/mediawiki/includes/OutputPage.php at line 623] in /var/www/mediawiki/includes/debug/MWDebug.php on line 300
PHP message: PHP Sta
2016/02/09 09:59:38 [error] 1005#0: *46831177 FastCGI sent in stderr: "www/mediawiki/includes/skins/SkinTemplate.php:465
PHP message: PHP   8. OutputPage->buildCssLinks() /var/www/mediawiki/includes/OutputPage.php:2714
PHP message: PHP   9. OutputPage->getModuleStyles() /var/www/mediawiki/includes/OutputPage.php:3668
PHP message: PHP  10. wfLogWarning() /var/www/mediawiki/includes/OutputPage.php:623
PHP message: PHP  11. MWDebug::warning() /var/www/mediawiki/includes/GlobalFunctions.php:1222
PHP message: PHP  12. MWDebug::sendMessage() /var/www/mediawiki/includes/debug/MWDebug.php:155
PHP message: PHP  13. trigger_error() /var/www/mediawiki/includes/debug/MWDebug.php:300" while reading response header from upstream, client: 172.16.77.12, server: mediawiki.afi-sa.fr, request: "GET /index.php?title=Accueil HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "mediawiki.afi-sa.fr", referrer: "http://mediawiki.afi-sa.fr/index.php?title=Sp%C3%A9cial:Connexion"
2016/02/09 09:59:38 [error] 1005#0: *46831180 connect() failed (111: Connection refused) while connecting to upstream, client: 172.16.77.12, server: mediawiki.afi-sa.fr, request: "GET /load.php?debug=false&lang=fr&modules=startup&only=scripts&skin=mediawikibootstrap HTTP/1.1", upstream: "fastcgi://[::1]:9000", host: "mediawiki.afi-sa.fr", referrer: "http://mediawiki.afi-sa.fr/index.php?title=Accueil"
</pre>

The repository seems clean and I didn't done any configuration...

Any idea ?

Regards,
Claire

**Comment by nasirkhan** [comment]
thanks for using this skin. I will look into the issue and will get back to you soon.

**Comment by BrunoRobert** [comment]
Hi,
I have the same problem on fresh installed Mediawiki:

`Warning: OutputPage::getModuleStyles: style module should define its position explicitly: skins.mediawikibootstrap ResourceLoaderFileModule [Called from OutputPage::getModuleStyles in /homepages/1/d182491366/htdocs/mediawiki/includes/OutputPage.php at line 623] in /homepages/1/d182491366/htdocs/mediawiki/includes/debug/MWDebug.php on line 300`

Bruno

**Comment by jdlrobson** [comment]
This should no longer be an issue in 1.35. The style position is redundant.
